server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: ${life.spring.profiles.active:dev}
  mvc:
    pathmatch:
      #swagger2的bug，只认这种方式，而springboot2.6默认已不是这种匹配模式。否则启动时报错
      #不配的话报：at springfox.documentation.spring.web.WebMvcPatternsRequestConditionWrapper.getPatterns
      matching-strategy: ANT_PATH_MATCHER
  application:
    #调用者feign只认spring.application.name，不认eureka.instance.appname配置应用名
    #所以不论服务提供者还是feign消费者，spring.application.name和eureka.instance.appname都配置就最好了
    #feign调用方大小写不区分，而注册中心永远显示为大写
    name: cj-life-auth
  redis:
    port: ${life.spring_redis_port:6379}
    database: ${life.spring_redis_db:0}
    password: ${life.spring_redis_pwd:123456}
    hostName: ${life.spring_redis_host:localhost}
  jta:
    atomikos:
      connectionfactory:
        max-lifetime:
#    sentinel:
#      master: local-master
#      nodes: 192.168.88.103:26380,192.168.88.103:26379
#      password: 123456
logging:
  level:
    root: info
life:
  security:
    auth_web:
      host: ${life.security_auth_web_host:http://localhost:8060}
      confirm_access_url: /confirm_access
      login_url: /login
    whitelist:
      - /login
      - /oauth/**
      - /logout
    static_resources:
      - /assets/**
      - /css/**
      - /images/**